spring:
  datasource:
    url: jdbc:postgresql://192.168.1.253/postgres
    driver-class-name: org.postgresql.Driver
    username: ez
    password: fz
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format-sql: true
        show-sql: true
    hibernate:
      ddl-auto: create-drop # create-drop: 시작과 종료에서 모두 drop > 데이터 날아감 , create, update, validate: 실서버 , none
