#  application.yml이 main.
# local: h2
# dev: mariadb
# test(staging): -
# prod: postgresql  -> 이런 경우는 잘 없음

#active : application-local.yml도 같이 활성화 # local, dev, prod

spring:
  profiles:
    active: local
