spring:
  datasource:
    url: jdbc:mariadb://192.168.1.253:3306/testdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: ezez
    password: fzfz
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format-sql: true
        show-sql: true
    hibernate:
      ddl-auto: create-drop # create-drop: 시작과 종료에서 모두 drop > 데이터 날아감 , create, update, validate: 실서버 , none
